### ISSUE TITLE
Don't crop images (support for non-square logos)

### ISSUE THREAD

**Issue by cconover** [Automattic/site-logo#10]
Since not all logos fit into a square format, but the user may want to keep their thumbnail settings to crop images, it would be nice to have the option when setting the logo whether or no to crop to a square, or just assume no cropping is wanted.

**Comment by iamtakashi** [comment]
From readme.txt

"The default is `thumbnail`, with other valid values being `medium`, `large`, `full`, and <b>any additional sizes declared by add_image_size.</b>"

You can specify any proportion with `add_image_size`.

**Comment by cconover** [comment]
Ah, I see. Nevermind then. Should've read more carefully :-)
