### ISSUE TITLE
Consider changing site logo anchor class name.

### ISSUE THREAD

**Issue by lukemcdonald** [Automattic/site-logo#12]
The site logo anchor has a class name of `site-logo-anchor`. It seems the majority of anchors in WP Core that have a class referencing the anchor use the term "link" in the class name as opposed to "anchor". One small example being `edit_post_link()`. 

At the risk of changing class names again and sounding to trivial, can we consider using `site-logo-link` as the class name for the anchor wrapping the site logo image element.

https://github.com/Automattic/site-logo/blob/master/inc/functions.php#L64
https://github.com/Automattic/site-logo/blob/master/inc/functions.php#L73

**Comment by kwight** [comment]
Hm, good point. I found a reference to Jetpack Sharing using `anchor`, but there's no core use of it that I could find.

There's also the Featured Images approach that would make the anchor `site-logo`, and the contained image `site-logo-image`.

Well spotted, will consider it more.

**Comment by thatryan** [comment]
I just came here to fork and make an edit to accomplish this, ha, guess I will wait and see what you decide. It would be very helpful to have a way to latch onto the anchor for the logo for styling purposes.
