### ISSUE TITLE
How to check if theme support for Site Logo is active

### ISSUE THREAD

**Issue by mtomas7** [Automattic/site-logo#13]
Hi, I'm not a big programmer, but managed to activate logo on my theme, but I faced problem - if plugin is deactivated, whole site goes blank.

What would be the code I could use in header.php that checks if Site Logo feature is active?

Thank you!

P.S. might be a good idea to add this info in README ;)

**Comment by samikeijonen** [comment]
Wrap it in function check like this:

```
<?php if ( function_exists( 'the_site_logo' ) ) the_site_logo(); ?>
```

**Comment by mtomas7** [comment]
Thank you!
