### ISSUE TITLE
What will happen when Site Logo gets put into Jetpack?

### ISSUE THREAD

**Issue by philiparthurmoore** [Automattic/site-logo#16]
I'm running Jetpack trunk and have noticed that most of the functions associated with Site Logo have now been prefixed with `jetpack_`. So what's ended up happening is that either the functions will work on localhost or WordPress.com, but not both right now. What will happen when someone who's been using Site Logo plugin upgrades their copy of Jetpack? I received fatal errors due to Site Logo and Jetpack running similar code, so proper checks should probably be put in place to avoid fatal errors when someone who's running Site Logo upgrades to the newest version of Jetpack, whenever Site Logo is put into it.

Also, shouldn't there be checks put into place to make sure that people who have been using nonprefixed functions won't have broken sites when they move over to using Site Logo inside of Jetpack?

**Comment by kwight** [comment]
Back-compat code has been added to Jetpack: 549ff74aa5e0654d98d68098ee9e074475538efe Sorry for the slow pickup on this issue :|
