### ISSUE TITLE
Logo Dimensions

### ISSUE THREAD

**Issue by cconover** [Automattic/site-logo#8]
It would be great if the user could specify logo dimensions, or at least a max dimension on either the X or Y axis.

**Comment by kwight** [comment]
You can, in CSS with `max-width` and `max-height`. This also allows compensating for retina, eg. using a 400x400 logo image size, with a `max-width` of 200px in your theme CSS.

**Comment by kwight** [comment]
Oh! Sorry, misread that. The idea was for it to be as simple as possible for the user: just upload whatever you've got, and the theme takes care of the rest. Giving cropping and size options just make it more complicated, like custom headers currently are.

**Comment by cconover** [comment]
Yeah, after using it with the theme I'm developing I agree with your approach.
